### ISSUE TITLE
Use Mocha and Gulp for testing

### ISSUE THREAD

**Issue by julianghionoiu** [julianghionoiu/tdl-runner-nodejs#6]

**Comment by neomatrix369** [comment]
Do you mean changin the package.json to default to mocha and gulp settings and when `npm build` or `npm test` is run, it uses the gulp and mocha runners?

**Comment by neomatrix369** [comment]
Will this affect the code coverage aspects of the workflow?

**Comment by neomatrix369** [comment]
Also why are we moving away from `ava`?

**Comment by neomatrix369** [comment]
Please also describe what Gulp tasks do you want created? What would you like to be run via gulp? Or just call gulp to do the build?

Just running tests via it?

**Comment by julianghionoiu** [comment]
We need a Gulp task to run the project and one to run the tests.

The code coverage script also needs updating.

**Comment by neomatrix369** [comment]
OK so here's what you also want the package.json to contain:

```nodejs
"scripts": {
    "start": "<some gulp command calling> ./lib/send_command_to_server.js",
    "test": "<some gulp command running tests in> ./node_modules/mocha/bin/mocha test/**/*.js",
    "coverage": "<some gulp command calling> nyc --reporter=json-summary --reporter=text ./node_modules/mocha/bin/mocha test/solutions/**/*.js"
  },
```

Basically replacing the need for calling `node` with `gulp`?

**Comment by neomatrix369** [comment]
The other way I'm thinking would be to invoke `npm start` or `npm test` from inside gulp tasks, which one are you in favour of?

**Comment by neomatrix369** [comment]
In case of gulp-cli/gulp issues, see https://github.com/pattern-lab/edition-node-gulp/wiki/Updating-to-Gulp-4
